name = "jurnalistempoupdate"
pages_build_output_dir = "./dist"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "jurnalistempo-db"
database_id = "YOUR_DATABASE_ID"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "jurnalistempo-media"
