name = "jurnalistempoupdate"

main = "src/index.ts"

compatibility_date = "2026-08-12"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "jurnalistempo-db"
database_id = "c34d8391-3ff0-46e5-bafe-90f3fda7edd1"
